stages:

    - build

    - deploy_gcp


build_images:

    stage: build

    image: docker:20.10.16

    services:

        - docker:20.10.16-dind

    variables:

        DOCKER_TLS_CERTDIR: "/certs"


    before_script:

        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

    script:

        - docker build -t denilsonbonatti/exemplo-app:1.0 backend/.

        - docker push denilsonbonatti/exemplo-app:1.0

        - docker build -t denilsonbonatti/projeto-database:1.0 database/.

        - docker push denilsonbonatti/projeto-database:1.0


deploy_gcp:

    stage: deploy_gcp

    before_script:

        - chmod 400 $SSH_KEY

    script:

        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo curl -O  https://gitlab.com/denilsonbonatti/cicd-kubernetes-gcp/-/blob/main/deployment.yml && sudo curl -O https://gitlab.com/denilsonbonatti/cicd-kubernetes-gcp/-/blob/main/services.yml && sudo kubectl apply -f ./services.yml && sudo kubectl apply -f ./deployment.yml"

